uploadLocation: /tmp/upload

p2palaConfigFile: /data/P2Pala_trainset/config.json

extractBaseLinesExecutorServiceConfig:
  maxThreads: 1
  name: ExtractBaselines
  queueLength: 50

cutFromImageBasedOnPageXmlExecutorServiceConfig:
  maxThreads: 1
  name: CutFromImage
  queueLength: 50

loghiHTRMergePageXMLResourceExecutorServiceConfig:
  maxThreads: 1
  name: CutFromImage
  queueLength: 50